version: '3.3'

services:
  web_app:
    container_name: django_mysite
    build:
      context: ./django_site
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/mysite/staticfiles
    ports:
      - "9999"
    env_file:
      - django_site/mysite.dev.env
    depends_on:
      - postgres_django
    networks:
      - net

  postgres_django:
    container_name: postgres_mysite
    env_file:
      - ./postgresql/pg.env
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    ports:
      - '4343:4343'
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
    command:
      - 'postgres'
      - '-c'
      - 'config_file=/var/lib/PostgresConfig/postgresql.conf'
    networks:
      - net

  nginx:
    container_name: nginx_proxy_mysite
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/mysite/staticfiles
    ports:
      - "7777:80"
    networks:
      - net
    depends_on:
      - postgres_django

networks:
  net:
    driver: bridge

volumes:
  static_volume:
